name: 'my_first_dbt_training'   # あなたのプロジェクト名
version: '1.0.0'
config-version: 2

profile: 'my_first_dbt_training'  # これはprofiles.ymlで設定する名前と一致させる

# これを追加または修正
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

models:
  my_first_dbt_training:
    +materialized: view